spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  threads:
    virtual:
      enabled: true

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  tracing:
    sampling:
      probability: 0.1

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: product-service
        url: /aggregate/openapi/product
    try-it-out-enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      productService:
        baseConfig: default
      orderService:
        baseConfig: default
      inventoryService:
        baseConfig: default
      paymentService:
        baseConfig: default
      customerService:
        baseConfig: default

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
